"""
Strategy Engine Module - Polymarket Spike Bot

Implements Mean Reversion / Spike Hunting strategy:
- Monitors mid-price in real-time
- Detects rapid price spikes (pump or dump)
- Places limit orders in the opposite direction to catch the rebound
"""

import asyncio
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Callable, Coroutine, Any

import structlog

from .config import BotConfig
from .market_connector import MarketConnector, OrderBook, OrderSide, Order
from .risk_manager import RiskManager, RiskStatus


logger = structlog.get_logger(__name__)


class SignalType(str, Enum):
    """Type of trading signal."""
    SPIKE_UP = "spike_up"      # Price pumped, expect mean reversion down
    SPIKE_DOWN = "spike_down"  # Price dumped, expect mean reversion up
    TAKE_PROFIT = "take_profit"
    STOP_LOSS = "stop_loss"


@dataclass
class PricePoint:
    """A single price observation."""
    timestamp: datetime
    price: float


@dataclass
class Signal:
    """Trading signal generated by the strategy."""
    type: SignalType
    token_id: str
    current_price: float
    reference_price: float
    change_percent: float
    suggested_side: OrderSide
    suggested_price: float
    confidence: float = 1.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class ActiveOrder:
    """Tracks an active order placed by the strategy."""
    order: Order
    signal: Signal
    placed_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    fill_timeout_seconds: float = 60.0


class StrategyEngine:
    """
    Mean Reversion / Spike Hunting Strategy.

    Algorithm:
    1. Track mid-price over a rolling window
    2. Detect when price moves more than X% within Y seconds
    3. If SPIKE UP (pump): Place SELL limit order below current price
    4. If SPIKE DOWN (dump): Place BUY limit order above current price
    5. Expect price to revert to mean, fill the order, then close for profit
    """

    def __init__(
        self,
        config: BotConfig,
        connector: MarketConnector,
        risk_manager: RiskManager,
    ):
        self.config = config
        self.connector = connector
        self.risk_manager = risk_manager

        # Strategy parameters
        self.spike_threshold = config.trading.spike_threshold_percent
        self.spike_window = config.trading.spike_window_seconds
        self.order_offset = config.trading.limit_order_offset_percent

        # Price history per token (token_id -> deque of PricePoints)
        self._price_history: dict[str, deque[PricePoint]] = {}

        # Active orders placed by strategy
        self._active_orders: dict[str, ActiveOrder] = {}

        # Signal callbacks
        self._signal_callbacks: list[Callable[[Signal], Coroutine[Any, Any, None]]] = []

        # Statistics
        self._signals_generated = 0
        self._orders_placed = 0
        self._orders_filled = 0

        logger.info(
            "StrategyEngine initialized",
            spike_threshold=f"{self.spike_threshold}%",
            spike_window=f"{self.spike_window}s",
            order_offset=f"{self.order_offset}%",
        )

    def on_signal(self, callback: Callable[[Signal], Coroutine[Any, Any, None]]) -> None:
        """Register callback for trading signals."""
        self._signal_callbacks.append(callback)

    async def process_orderbook(self, orderbook: OrderBook) -> Signal | None:
        """
        Process an order book update.

        Checks for spike conditions and generates signals.
        """
        token_id = orderbook.token_id
        mid_price = orderbook.mid_price

        if mid_price is None or mid_price <= 0:
            return None

        now = datetime.now(timezone.utc)

        # Update risk manager with new price
        self.risk_manager.update_price(token_id, mid_price)

        # Initialize price history if needed
        if token_id not in self._price_history:
            # Keep 2x the window size for safety
            max_points = int(self.spike_window * 10)  # Assume ~10 updates per second max
            self._price_history[token_id] = deque(maxlen=max(max_points, 100))

        # Add new price point
        self._price_history[token_id].append(PricePoint(timestamp=now, price=mid_price))

        # Check for existing position - handle stop loss / take profit
        position = self.risk_manager.get_position(token_id)
        if position:
            signal = await self._check_position_exit(token_id, mid_price)
            if signal:
                return signal

        # Check for spike signal (only if no active order for this token)
        if token_id not in self._active_orders:
            signal = self._detect_spike(token_id, mid_price, now)
            if signal:
                await self._emit_signal(signal)
                return signal

        return None

    def _detect_spike(
        self,
        token_id: str,
        current_price: float,
        now: datetime,
    ) -> Signal | None:
        """
        Detect if a price spike has occurred.

        A spike is defined as price moving > threshold% within the window.
        """
        history = self._price_history.get(token_id)
        if not history or len(history) < 2:
            return None

        # Find price at the start of the window
        window_start = now - timedelta(seconds=self.spike_window)

        # Get the oldest price within the window
        reference_price = None
        for point in history:
            if point.timestamp >= window_start:
                reference_price = point.price
                break

        if reference_price is None or reference_price <= 0:
            return None

        # Calculate percentage change
        change_percent = ((current_price - reference_price) / reference_price) * 100

        # Check if change exceeds threshold
        if abs(change_percent) < self.spike_threshold:
            return None

        # Determine signal type and suggested action
        if change_percent > 0:
            # Price spiked UP -> expect reversion DOWN -> SELL
            signal_type = SignalType.SPIKE_UP
            suggested_side = OrderSide.SELL
            # Place limit order slightly below current price to catch the drop
            suggested_price = current_price * (1 - self.order_offset / 100)
        else:
            # Price spiked DOWN -> expect reversion UP -> BUY
            signal_type = SignalType.SPIKE_DOWN
            suggested_side = OrderSide.BUY
            # Place limit order slightly above current price to catch the bounce
            suggested_price = current_price * (1 + self.order_offset / 100)

        # Calculate confidence based on spike magnitude
        # Larger spikes = higher confidence (up to a point)
        confidence = min(abs(change_percent) / self.spike_threshold, 2.0) / 2.0

        signal = Signal(
            type=signal_type,
            token_id=token_id,
            current_price=current_price,
            reference_price=reference_price,
            change_percent=change_percent,
            suggested_side=suggested_side,
            suggested_price=suggested_price,
            confidence=confidence,
        )

        self._signals_generated += 1

        logger.info(
            "Spike detected",
            token_id=token_id,
            signal_type=signal_type.value,
            change=f"{change_percent:+.2f}%",
            current_price=current_price,
            reference_price=reference_price,
            suggested_action=f"{suggested_side.value} @ {suggested_price:.4f}",
            confidence=f"{confidence:.2f}",
        )

        return signal

    async def _check_position_exit(
        self,
        token_id: str,
        current_price: float,
    ) -> Signal | None:
        """Check if an existing position should be closed."""
        # Check stop loss
        if self.risk_manager.check_stop_loss(token_id, current_price):
            position = self.risk_manager.get_position(token_id)
            if position:
                signal = Signal(
                    type=SignalType.STOP_LOSS,
                    token_id=token_id,
                    current_price=current_price,
                    reference_price=position.entry_price,
                    change_percent=position.unrealized_pnl,
                    suggested_side=OrderSide.SELL if position.side == OrderSide.BUY else OrderSide.BUY,
                    suggested_price=current_price,
                    confidence=1.0,
                )
                await self._emit_signal(signal)
                return signal

        # Check take profit
        if self.risk_manager.check_take_profit(token_id, current_price):
            position = self.risk_manager.get_position(token_id)
            if position:
                signal = Signal(
                    type=SignalType.TAKE_PROFIT,
                    token_id=token_id,
                    current_price=current_price,
                    reference_price=position.entry_price,
                    change_percent=position.unrealized_pnl,
                    suggested_side=OrderSide.SELL if position.side == OrderSide.BUY else OrderSide.BUY,
                    suggested_price=current_price,
                    confidence=1.0,
                )
                await self._emit_signal(signal)
                return signal

        return None

    async def _emit_signal(self, signal: Signal) -> None:
        """Emit signal to all registered callbacks."""
        for callback in self._signal_callbacks:
            try:
                await callback(signal)
            except Exception as e:
                logger.error("Signal callback error", error=str(e))

    async def execute_signal(self, signal: Signal) -> Order | None:
        """
        Execute a trading signal.

        Checks risk, places order, and tracks it.
        """
        token_id = signal.token_id

        # Calculate position size
        size = self.risk_manager.calculate_position_size(signal.suggested_price)
        if size <= 0:
            logger.warning("Cannot calculate position size", token_id=token_id)
            return None

        # Check risk
        risk_check = self.risk_manager.check_trade(
            token_id=token_id,
            side=signal.suggested_side,
            size=size,
            price=signal.suggested_price,
        )

        if risk_check.status != RiskStatus.APPROVED:
            logger.warning(
                "Trade rejected by risk manager",
                token_id=token_id,
                reason=risk_check.reason,
                details=risk_check.details,
            )
            return None

        # Place order
        try:
            order = await self.connector.place_order(
                token_id=token_id,
                side=signal.suggested_side,
                price=signal.suggested_price,
                size=size,
            )

            # Record trade
            self.risk_manager.record_trade(
                token_id=token_id,
                side=signal.suggested_side,
                price=signal.suggested_price,
                size=size,
            )

            # Track active order
            self._active_orders[token_id] = ActiveOrder(order=order, signal=signal)
            self._orders_placed += 1

            logger.info(
                "Order placed",
                order_id=order.id,
                token_id=token_id,
                side=signal.suggested_side.value,
                price=signal.suggested_price,
                size=size,
                signal_type=signal.type.value,
            )

            return order

        except Exception as e:
            logger.error(
                "Failed to place order",
                token_id=token_id,
                error=str(e),
            )
            return None

    async def handle_exit_signal(self, signal: Signal) -> Order | None:
        """
        Handle stop loss or take profit signal.

        Immediately closes the position at market.
        """
        position = self.risk_manager.get_position(signal.token_id)
        if not position:
            return None

        # Close position
        pnl = self.risk_manager.close_position(signal.token_id, signal.current_price)

        # Place market order to close (in real implementation)
        try:
            order = await self.connector.place_order(
                token_id=signal.token_id,
                side=signal.suggested_side,
                price=signal.current_price,  # Market order simulated as limit at current
                size=position.size,
            )

            # Remove from active orders if exists
            if signal.token_id in self._active_orders:
                del self._active_orders[signal.token_id]

            logger.info(
                "Position closed",
                order_id=order.id,
                token_id=signal.token_id,
                exit_type=signal.type.value,
                pnl=f"${pnl:.2f}",
            )

            return order

        except Exception as e:
            logger.error(
                "Failed to close position",
                token_id=signal.token_id,
                error=str(e),
            )
            return None

    async def check_order_timeouts(self) -> None:
        """Check for orders that have timed out and should be cancelled."""
        now = datetime.now(timezone.utc)
        to_cancel = []

        for token_id, active_order in self._active_orders.items():
            elapsed = (now - active_order.placed_at).total_seconds()
            if elapsed > active_order.fill_timeout_seconds:
                to_cancel.append(token_id)

        for token_id in to_cancel:
            active_order = self._active_orders.pop(token_id)
            try:
                await self.connector.cancel_order(active_order.order.id)
                logger.info(
                    "Order cancelled (timeout)",
                    order_id=active_order.order.id,
                    token_id=token_id,
                    elapsed=f"{(now - active_order.placed_at).total_seconds():.1f}s",
                )
            except Exception as e:
                logger.error(
                    "Failed to cancel timed out order",
                    order_id=active_order.order.id,
                    error=str(e),
                )

    def get_statistics(self) -> dict[str, Any]:
        """Get strategy statistics."""
        return {
            "signals_generated": self._signals_generated,
            "orders_placed": self._orders_placed,
            "orders_filled": self._orders_filled,
            "active_orders": len(self._active_orders),
            "monitored_tokens": len(self._price_history),
        }

    def reset_price_history(self, token_id: str | None = None) -> None:
        """Reset price history for a token or all tokens."""
        if token_id:
            if token_id in self._price_history:
                self._price_history[token_id].clear()
        else:
            for history in self._price_history.values():
                history.clear()


class MultiMarketStrategy:
    """
    Manages strategy execution across multiple markets.

    Coordinates order book subscriptions and signal processing
    for all configured markets.
    """

    def __init__(
        self,
        config: BotConfig,
        connector: MarketConnector,
        risk_manager: RiskManager,
    ):
        self.config = config
        self.connector = connector
        self.risk_manager = risk_manager

        self.engine = StrategyEngine(config, connector, risk_manager)

        # Track monitored markets
        self._monitored_tokens: set[str] = set()

        # Setup orderbook callback
        self.connector.on_orderbook_update(self._on_orderbook_update)

    async def start(self, token_ids: list[str]) -> None:
        """Start monitoring specified tokens."""
        for token_id in token_ids:
            await self.add_market(token_id)

    async def add_market(self, token_id: str) -> None:
        """Add a market to monitoring."""
        if token_id in self._monitored_tokens:
            return

        self._monitored_tokens.add(token_id)
        await self.connector.subscribe_orderbook(token_id)

        logger.info("Added market to monitoring", token_id=token_id)

    async def remove_market(self, token_id: str) -> None:
        """Remove a market from monitoring."""
        if token_id not in self._monitored_tokens:
            return

        self._monitored_tokens.discard(token_id)
        await self.connector.unsubscribe_orderbook(token_id)

        logger.info("Removed market from monitoring", token_id=token_id)

    async def _on_orderbook_update(self, orderbook: OrderBook) -> None:
        """Handle order book update from WebSocket."""
        signal = await self.engine.process_orderbook(orderbook)

        if signal:
            if signal.type in (SignalType.STOP_LOSS, SignalType.TAKE_PROFIT):
                await self.engine.handle_exit_signal(signal)
            elif signal.type in (SignalType.SPIKE_UP, SignalType.SPIKE_DOWN):
                await self.engine.execute_signal(signal)

    async def run_maintenance(self) -> None:
        """Run periodic maintenance tasks."""
        while True:
            try:
                # Check for order timeouts
                await self.engine.check_order_timeouts()

                # Log status periodically
                stats = self.engine.get_statistics()
                risk_status = self.risk_manager.get_risk_status()

                logger.debug(
                    "Strategy status",
                    signals=stats["signals_generated"],
                    orders_placed=stats["orders_placed"],
                    active_orders=stats["active_orders"],
                    open_positions=risk_status["open_positions"],
                    daily_pnl=f"${risk_status['daily_pnl']:.2f}",
                )

            except Exception as e:
                logger.error("Maintenance error", error=str(e))

            await asyncio.sleep(10)  # Run every 10 seconds

    def get_monitored_tokens(self) -> set[str]:
        """Get set of monitored token IDs."""
        return self._monitored_tokens.copy()
